name: designate
display_name: Designate
service_type: dns
defaults:
  actions:
  - log
  - delete
  - tag
  checks:
  - status
  - age_gt
  - unused
  - exempt_names
resources:
  zone:
    description: DNS zones
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
  recordset:
    description: DNS recordsets
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
  record:
    description: DNS records
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
