name: magnum
display_name: Magnum
service_type: container-infra
defaults:
  actions:
  - log
  - delete
  - tag
  checks:
  - status
  - age_gt
  - unused
  - exempt_names
resources:
  cluster:
    description: Container clusters
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
  cluster_template:
    description: Cluster templates
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
  bay:
    description: Bays (deprecated)
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
  baymodel:
    description: Bay models (deprecated)
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
