name: senlin
display_name: Senlin
service_type: clustering
defaults:
  actions:
  - log
  - delete
  - tag
  checks:
  - status
  - age_gt
  - unused
  - exempt_names
resources:
  cluster:
    description: Clusters
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
  profile:
    description: Profiles
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
  node:
    description: Nodes
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
  policy:
    description: Policies
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
