name: swift
display_name: Swift
service_type: object-store
defaults:
  actions:
  - log
  - delete
  - tag
  checks:
  - status
  - age_gt
  - unused
  - exempt_names
resources:
  container:
    description: Containers
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
  object:
    description: Objects
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
  account:
    description: Accounts
    actions:
    - log
    - delete
    - tag
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
